openapi: "3.0.2"
info:
  description: "これはTEAM-MAKERに関するAPIです。"
  version: "0.0.1"
  title: "TEAM-MAKER API"
  termsOfService: "http://teammaker.com" # 仮定義
  contact:
    email: "system@teammaker.info"
# paths: # TODO: 後で定義する
servers:
  - url: "http://localhost:8888"
    description: ローカルサーバ
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  "/api/v1/page/{id}":
    get:
      summary: "求人レコードの取得エンドポイント"
      description: "求人レコードの取得エンドポイント"
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "ページ詳細"
          content:
            "application/json":
              schema:
                type: object
                required:
                  - id
                  - name
                properties:
                  id:
                    title: ページID
                    type: number
                    readOnly: true
                    example: 1
                  company_id:
                    title: 会社ID
                    type: string
                    example: 2
                  meta:
                    title: メタタグ
                    type: json
                    example: {}
                  content:
                    title: コンテンツ
                    type: string
                    example: ページ種別に依存しないコンテンツ
                  job:
                    title: 求人
                    type: json
                    example: { 
                      id: 1, 
                      employment_category_id: 1,
                      code: 管理用コード,
                      name: 港区で働く訪問看護師,
                      job_content: 業務内容,
                      contract_period: {},
                      welfare: 福利厚生,
                      industry: {},
                      work_datetime: {},
                      salary: {},
                      place: {},
                      info: {},
                      published_at: 2020-09-04 15:25:07,
                      expired_at: 2020-11-04 15:25:07
                    }
                  released_at:
                    title: 公開日
                    type: string
                    example: 2020-10-04 15:25:07
definitions:
  Company:
    description: "求人企業情報"
    type: "object"
    properties:

  User:
    description: "システムにログインするユーザー。管理者と社員を想定"
    type: "object"
    properties:

  Incentive:
    description: "社員が紹介した求人が内定すると貯まるインセンティブ。"
    type: "object"
    properties:

  Job:
    type: "object"
    description: "求人情報"
    properties:
      company:
        $ref: "#/definitions/Company"

  Application:
    type: "object"
    description: "社員から紹介された求人応募情報"
    properties:
      job:
        description: "求人情報"
        $ref: "#/definitions/Job"
      introducer:
        description: "求人紹介した社員"
        $ref: "#/definitions/User"
      applicant:
        description: "求人に応募する人"
        $ref: "#/definitions/Applicant"
      status:
        description: "#応募/面談/内定/削除 などのステータス"
        $ref: "#/definitions/Status"

  Applicant:
    type: "object"
    description: "求人に応募する人"
    properties:

  Status:
    type: "object"
    description: "#応募/面談/内定/削除 などのステータス"
    properties:
