openapi: "3.0.2"
info:
  description: "これはTEAM-MAKERに関するAPIです。"
  version: "0.0.1"
  title: "TEAM-MAKER API"
  termsOfService: "http://teammaker.com" # 仮定義
  contact:
    email: "system@teammaker.info"
paths:
  "/api/v1/page/{slug}":
    get:
      summary: "ページコンテンツ取得エンドポイント"
      description: "ページコンテンツ取得エンドポイント"
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "ページ詳細"
          content:
            "application/json":
              schema:
                type: object
                required:
                  - id
                  - name
                properties:
                  id:
                    title: ページID
                    type: number
                    readOnly: true
                    example: 1
                  company_id:
                    title: 会社ID
                    type: string
                    example: 2
                  meta:
                    type: object
                    properties:
                      title: タイトル
                      type: string
                      example: タイトル
                  content:
                    type: object
                    properties:
                      common_content:
                        title: ページ種別に依存しないコンテンツ
                        type: string
                        example: ページ種別に依存しないコンテンツサンプル
                      pageable_content:
                        type: object
                        properties:
                          type:
                            title: コンテンツのタイプ
                            type: string
                            enum: [job, facilities, wysiwyg]
                            example: job
                          record:
                            type: object
                            properties:
                              id:
                                title: コンテンツのID
                                type: number
                                example: 1
                              employment_category_id:
                                title: 就業形態
                                type: number
                                example: 1
                              code:
                                title: 管理用コード
                                type: number
                                example: 72
                              name:
                                title: 求人のタイトル
                                type: string
                                example: Jerrod Jenkins
                              job_content:
                                title: 業務内容
                                type: string
                                example: Magnam autem tempora voluptatem numquam. In nulla ut animi in et nulla.
                              contract_period:
                                type: object
                                properties:
                                  finished_at:
                                    title: 契約期間
                                    type: string
                                    example:
                              welfare:
                                title: 福利厚生
                                type: string
                                example: ◇ 労災保険
                              industry:
                                type: object
                                properties:
                                  industry:
                                    title: 業界
                                    type: string
                                    example: 
                                  occupation:
                                    title: 職業
                                    type: string
                                    example:
                              work_datetime:
                                type: object
                                properties:
                              salary:
                                type: object
                                properties: 
                                  hourly:
                                    title: 時給
                                    type: string
                                    example:
                              place:
                                title: 勤務地
                                type: string
                                example: 315 Torp Cliffs Apt. 455
                              info:
                                type: object
                                properties:
                              published_at:
                                title: 掲載開始日
                                type: string
                                example: 2020-09-04 15:25:07
                              expired_at:
                                title: 有効期限
                                type: string
                                example: expired_at            
                  released_at:
                    title: 公開日
                    type: string
                    example: 2020-10-04 15:25:07
definitions:
  Company:
    description: "求人企業情報"
    type: "object"
    properties:

  User:
    description: "システムにログインするユーザー。管理者と社員を想定"
    type: "object"
    properties:

  Incentive:
    description: "社員が紹介した求人が内定すると貯まるインセンティブ。"
    type: "object"
    properties:

  Job:
    type: "object"
    description: "求人情報"
    properties:
      company:
        $ref: "#/definitions/Company"

  Application:
    type: "object"
    description: "社員から紹介された求人応募情報"
    properties:
      job:
        description: "求人情報"
        $ref: "#/definitions/Job"
      introducer:
        description: "求人紹介した社員"
        $ref: "#/definitions/User"
      applicant:
        description: "求人に応募する人"
        $ref: "#/definitions/Applicant"
      status:
        description: "#応募/面談/内定/削除 などのステータス"
        $ref: "#/definitions/Status"

  Applicant:
    type: "object"
    description: "求人に応募する人"
    properties:

  Status:
    type: "object"
    description: "#応募/面談/内定/削除 などのステータス"
    properties:

