openapi: "3.0.2"
info:
  description: "これはTEAM-MAKERに関するAPIです。"
  version: "0.0.1"
  title: "TEAM-MAKER API"
  termsOfService: "http://teammaker.com" # 仮定義
  contact:
    email: "system@teammaker.info"
paths:
  "/api/v1/page/{slug}":
    get:
      summary: "ページコンテンツ取得エンドポイント"
      description: "ページコンテンツ取得エンドポイント"
      parameters:
        - in: path
          name: slug
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "ページ詳細"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/Page"
components:
  schemas:
    Page:
      type: object
      required:
        - id
        - name
      properties:
        id:
          title: ページID
          type: number
          readOnly: true
          example: 1
        company:
          $ref: "#/components/schemas/Company"
        meta:
          type: object
          properties:
            title:
              title: タイトル
              type: string
              example: サンプルタイトル
        content:
          type: object
          properties:
            common_content:
              title: ページ種別に依存しないコンテンツ
              type: string
              example: ページ種別に依存しないコンテンツサンプル
            pageable_content:
              title: ポリモーフィック
              type: object
              properties:
                type:
                  title: コンテンツタイプ
                  type: string
                  enum: [job]
                  example: job
                record:
                  $ref: "#/components/schemas/Job"
        released_at:
          title: 公開日
          type: string
          example: 2020-10-04 15:25:07
    Job:
      type: object
      properties:
        id:
          title: コンテンツのID
          type: number
          example: 1
        employment_category:
          type: object
          properties:
            id:
              title: 雇用タイプのID
              type: number
              example: 1
            name:
              title: 雇用タイプ
              type: string
              example: 正社員  
        code:
          title: 管理用コード
          type: string
          example: 476828240
        name:
          title: 求人のタイトル
          type: string
          example: Jerrod Jenkins
        job_content:
          title: 業務内容
          type: string
          example: Magnam autem tempora voluptatem numquam. In nulla ut animi in et nulla.
        contract_period:
          type: object
          properties:
        welfare:
          title: 福利厚生
          type: string
          example: ◇ 労災保険
        industry:
          type: object
          properties:
            industry:
              title: 業界
              type: string
              example:
            occupation:
              title: 職業
              type: string
              example:
        work_datetime:
          type: object
          properties:
        salary:
          type: object
          properties:
            hourly:
              title: 時給
              type: string
              example:
        place:
          title: 勤務地
          type: string
          example: 315 Torp Cliffs Apt. 455
        info:
          type: object
          properties:
        published_at:
          title: 掲載開始日
          type: string
          example: 2020-09-04 15:25:07
        expired_at:
          title: 有効期限
          type: string
          example: expired_at
    Company:
      type: object
      properties:
        name:
          title: 会社名
          type: string
          example: サンプル会社
        unique_id:
          title: 会社ID
          type: string
          example: 5e55sss2dc291d
